### ISSUE TITLE
'VRInitError_Init_VRClientDLLNotFound (error number 102)'

### ISSUE THREAD

**Issue by tony2012** [moon-wreckers/vive_tracker#1]
After setup according  to the guide, I got an error:

An exception of type OpenVRError occurred. Arguments:
('VRInitError_Init_VRClientDLLNotFound (error number 102)',)

How did that happen?
It seems the node can not find openvr library.

**Comment by DanielArnett** [comment]
Okay, this seems to be a pyopenvr error. Try this command to make a symbolic link of libudev.so.1. 

`sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0`

[This thread has more discussion on the error.](https://github.com/cmbruns/pyopenvr/issues/30) Let me know if this does the trick for you so I know whether to close the issue.

**Comment by tony2012** [comment]
Thanks, I have done the symbolic link, nothing changed.

**Comment by DanielArnett** [comment]
1. Do you have libudev-dev installed?
2. Are both of these files showing up in the correct place? /lib/x86_64-linux-gnu/libudev.so.1 
/lib/x86_64-linux-gnu/libudev.so.0
