### ISSUE TITLE
Unable to track with one base-station and tracker

### ISSUE THREAD

**Issue by danmartinez78** [moon-wreckers/vive_tracker#2]
I've tried with two base-stations and tracker with no issues. Attempting to use one base station set to "A" and the tracker is not working. Both devices show up in steamVR but have status of not tracking. Any guidance on this?

**Comment by DanielArnett** [comment]
Yes, first try moving the tracker a little bit, I believe SteamVR won't
start tracking until it can detect movement. Second, if that doesn't work
try turning off the tracker (I recommend by right clicking the green
tracker icon in SteamVR), plugging the tracker into your computer,
restarting SteamVR, and turning your tracker back on.

As always with SteamVR on Ubuntu: restart your computer often.

**Comment by danmartinez78** [comment]
Moving the tracker around worked. Thanks!

**Comment by DanielArnett** [comment]
@danmartinez78 glad to hear. I hope the tracker turns out to be useful in your project!
