### ISSUE TITLE
process has died

### ISSUE THREAD

**Issue by vkguda355** [moon-wreckers/vive_tracker#3]
HI i am using this package, and when i launch it, i get this error 

> [vive/vive_tracker-5] process has died [pid 13767, exit code 1, cmd /home/vkguda/catkin_ws/src/vive_tracker/scripts/vive_tracker.py __name:=vive_tracker __log:=/home/vkguda/.ros/log/533df952-967e-11e9-a264-34e12dcd93f8/vive-vive_tracker-5.log].
log file: /home/vkguda/.ros/log/533df952-967e-11e9-a264-34e12dcd93f8/vive-vive_tracker-5*.log

> 
![Screenshot from 2019-06-24 14-56-00](https://user-images.githubusercontent.com/29279087/60020465-5eb6b500-9690-11e9-97e3-485044bab9af.png)

any reasons why i get this error?

**Comment by DanielArnett** [comment]
Is SteamVR running and do you see a solid green Vive tracker icon?

**Comment by vkguda355** [comment]
yes, the steam vr is running fine. is that error related to 

> ImportError: No module named openvr

**Comment by vkguda355** [comment]
also, the step to create a symbolic link, when i run that command. i get a message saying that 

> /lib/x86_64-linux-gnu/libudev.so.0 File exits, 
i checked that the file 'libudev.so.o' is in /home/user/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu and is linled to a different file "libudev.so.0.13.0" in the same folder.
 and libudev.so.1 is not linked to any thing. do u think this could ahve caused any issues?

so i had skipped that step.

**Comment by vkguda355** [comment]
I will walk you through what i did following your tutorial.

instead of downloading the file and following the steps u said specified, (because i did not understand your steps, my mistake i am new to ubuntu and ros) had followed the steps in the link you have provided, they had to given 4 step to install the Vulkan

`wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.108-bionic.list http://packages.lunarg.com/vulkan/1.1.108/lunarg-vulkan-1.1.108-bionic.list
sudo apt update
sudo apt install vulkan-sdk`

i had installed steam, created account, changed the account to beta one. added the dependencies for openVR, had done the symbolic link. installed pyopnevr, (ps: i have python 3.6 and also 2.7)

i did not disable the headset because , i have a headset. so i skipped those steps. finally installed the vive_tracker.launch file and run it to find the importERRor. and the error message i had posted.

i hope this would help you.

**Comment by DanielArnett** [comment]
It seems like you knew what you were doing, having the headset saves a lot
of headache. Know what fixed your problem?
