### ISSUE TITLE
ROS/TF quaternion notation

### ISSUE THREAD

**Issue by HWiese1980** [moon-wreckers/vive_tracker#4]
https://github.com/moon-wreckers/vive_tracker/blob/374ebafd60278a48f5a519b26019d96a8329b1eb/scripts/triad_openvr.py#L117

ROS quaternion notation is [X, Y, Z, W]. Wonder why it works this way. 

Source: http://wiki.ros.org/tf2/Tutorials/Quaternions

**Comment by DanielArnett** [comment]
[That part was  written by Triad, the manufacturer of Vive's tracking system. Here's where that file came from.](http://help.triadsemi.com/en/articles/836917-steamvr-tracking-without-an-hmd)
